#Predict Horse or Human

here we are loading train CNN model to predict Given(image) is Horse of human

In [30]:
#load lab
import numpy as np
import keras
# from keras.preprocessing import image
# import keras.utils as image

# import keras.utils as image


Import Model

In [31]:
model_path1 = '/content/drive/MyDrive/horse-or-human/horse_or_human_predictor.h5'

model1 = keras.models.load_model(model_path1)

Preprocessing

In [32]:
#horse images path
h1 = '/content/drive/MyDrive/horse-or-human/horse-or-human/train/horses/horse01-0.png'
h2 =  '/content/drive/MyDrive/horse-or-human/horse-or-human/train/horses/horse01-1.png'
h3 =  '/content/drive/MyDrive/horse-or-human/horse-or-human/train/horses/horse01-2.png'
h4 =  '/content/drive/MyDrive/horse-or-human/horse-or-human/train/horses/horse01-3.png'
h5 =  '/content/drive/MyDrive/horse-or-human/horse-or-human/train/horses/horse01-4.png'

#human images path
hu1 = '/content/drive/MyDrive/horse-or-human/horse-or-human/train/humans/human01-00.png'
hu2 = '/content/drive/MyDrive/horse-or-human/horse-or-human/train/humans/human01-02.png'
hu3 = '/content/drive/MyDrive/horse-or-human/horse-or-human/train/humans/human01-03.png'
hu4 = '/content/drive/MyDrive/horse-or-human/horse-or-human/train/humans/human01-04.png'
hu5 = '/content/drive/MyDrive/horse-or-human/horse-or-human/train/humans/human01-05.png'


In [37]:
import numpy as np
from keras.preprocessing import image
import tensorflow as tf
import keras.utils as image

#Copy from here
def pred_human_horse(model, horse_or_human):
  test_image = tf.keras.preprocessing.image.load_img(horse_or_human, target_size=(150,150))
  test_image = image.img_to_array(test_image)/255
  test_image = np.expand_dims(test_image, axis = 0)

  result = model.predict(test_image).round(3)

  pred = np.argmax(result)
  print(result, "-->>>", pred)

  if pred == 0:
    print('Predicated>>> Horse')
  
  else:
    print("Predicated>>> Human")


Predict Output

In [38]:
for horse_or_human in [h1,h2,h3,h4,h5, hu1,hu2,hu3,hu4,hu5]:
  pred_human_horse(model1, horse_or_human)

1/1 [==============================] - 1s 602ms/step
[[0.604 0.396]] -->>> 0
Predicated>>> Horse
1/1 [==============================] - 0s 65ms/step
[[0.825 0.175]] -->>> 0
Predicated>>> Horse
1/1 [==============================] - 0s 66ms/step
[[0.854 0.146]] -->>> 0
Predicated>>> Horse
1/1 [==============================] - 0s 60ms/step
[[0.848 0.152]] -->>> 0
Predicated>>> Horse
1/1 [==============================] - 0s 67ms/step
[[0.844 0.156]] -->>> 0
Predicated>>> Horse
1/1 [==============================] - 0s 64ms/step
[[0.222 0.778]] -->>> 1
Predicated>>> Human
1/1 [==============================] - 0s 58ms/step
[[0.217 0.783]] -->>> 1
Predicated>>> Human
1/1 [==============================] - 0s 64ms/step
[[0.213 0.787]] -->>> 1
Predicated>>> Human
1/1 [==============================] - 0s 39ms/step
[[0.219 0.781]] -->>> 1
Predicated>>> Human
1/1 [==============================] - 0s 41ms/step
[[0.231 0.769]] -->>> 1
Predicated>>> Human
